### ISSUE TITLE
how can I use cuda tensor

### ISSUE THREAD

**Issue by cha0s-repo** [randaller/llama-chat#11]
Hi randaller,
I tried to use cuda tensor type by uncommenting this line "torch.set_default_tensor_type(torch.cuda.HalfTensor)" in example. But got error like this:
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)

My question is how can I use cuda type within your example?
Thanks in advance.
Kyle

**Comment by randaller** [comment]
@cha0s-repo fp16 tensors not supported by pytorch on CPU.
