### ISSUE TITLE
Hello, how to make the output be trimed?

### ISSUE THREAD

**Issue by jinfagang** [randaller/llama-chat#2]
<img width="1179" alt="图片" src="https://user-images.githubusercontent.com/21303438/224013702-8c95dcdc-1b45-4657-b700-16e46a7bcb2f.png">

curretnly outputs all inference steps and results, is there  a way print only answer?

**Comment by jinfagang** [comment]
@randaller how many 30B cpu mem needed to inference? I adopted this to inference on GPU with 16GB mem, seems fast, but the promots not really well

**Comment by randaller** [comment]
> how many 30B cpu mem needed to inference?

About 70 gigabytes of RAM needed. It should work with any amount of RAM, just very slowly, systems will use swap file hardly.
