### ISSUE TITLE
Feature Request - Ways to add context to conversation from beginning.

### ISSUE THREAD

**Issue by bradgillap** [randaller/llama-chat#24]
Some way to input contextual data within the web interface. Maybe through uploading documents, json files, providing lists of weblinks.

I'm not sure what's possible with the py library so please ignore if this is ridiculous as an ask.

**Comment by randaller** [comment]
@bradgillap ctx = """
... here goes any text data up to 2048 tokens and your query for model to continue generation ...
"""
