### ISSUE TITLE
why does this happen?

### ISSUE THREAD

**Issue by breadbrowser** [randaller/llama-chat#4]
PS F:\downloads\llama-chat-main\llama-chat-main> python3.7 merge-weights.py --input_dir F:\Downloads\LLaMA --model_size 13B
Traceback (most recent call last):
  File "merge-weights.py", line 168, in <module>
    main()
  File "merge-weights.py", line 163, in main
    model_size=args.model_size,
  File "merge-weights.py", line 95, in write_model
    f"layers.{layer_i}.ffn_norm.weight": loaded[0][f"layers.{layer_i}.ffn_norm.weight"],
TypeError: unsupported operand type(s) for |=: 'dict' and 'dict'

**Comment by nazthelizard122** [comment]
Same issue

I've tried on python 3.8 and 3.11, I don't think the versions matter much 
Attempted to troubleshoot with chatGPT's advice to no avail

**Comment by breadbrowser** [comment]
python 3.8.10 fixed it for me.

now i just need 317214720 bytes more of memory.

**Comment by nazthelizard122** [comment]
I'm on Mac, conda cant find 3.8.10

**Comment by Chting** [comment]
The merge (|) and update (|=) operators of the dictionary were introduced in Python 3.9

**Comment by tkone2018** [comment]
@breadbrowser i also met the error,how can i do?

**Comment by randaller** [comment]
Use python 3.9 or higher. There is 3.10 version noted in example.

**Comment by breadbrowser** [comment]
> I'm on Mac, conda cant find 3.8.10

https://www.python.org/downloads/release/python-3810/

**Comment by breadbrowser** [comment]
> @breadbrowser i also met the error,how can i do?

try doing it without conda

**Comment by breadbrowser** [comment]
> Use python 3.9 or higher. There is 3.10 version noted in example.

python 3.8.10 is what colab and kaggle use

**Comment by breadbrowser** [comment]
> Use python 3.9 or higher. There is 3.10 version noted in example.

I was wrong, he is right python 3.10 fixed it for me
