### ISSUE TITLE
It's too slow, how run 30B on 4 GPUs interactively

### ISSUE THREAD

**Issue by zhongtao93** [randaller/llama-chat#6]

**Comment by tkone2018** [comment]
@zhongtao93 hello, can you solve it?

**Comment by zhongtao93** [comment]
No~

**Comment by zhongtao93** [comment]
> @zhongtao93 hello, can you solve it?
The expert has solved this problem
https://github.com/facebookresearch/llama/issues/162#issuecomment-1464996569
