### ISSUE TITLE
Error on run: size mismatch for ...

### ISSUE THREAD

**Issue by MartinKlefas** [randaller/llama-chat#9]
I've managed to complete all the steps but the last, and when I run
'python example-chat.py ./model ./tokenizer/tokenizer.model'

I wait a few minutes then get a lot of error lines like:
```
size mismatch for tok_embeddings.weight: copying a param with shape torch.Size([32000, 6656]) from checkpoint, the shape in current model is torch.Size([32000, 5120]).
size mismatch for layers.39.ffn_norm.weight: copying a param with shape torch.Size([6656]) from checkpoint, the shape in current model is torch.Size([5120]).
        size mismatch for norm.weight: copying a param with shape torch.Size([6656]) from checkpoint, the shape in current model is torch.Size([5120]).
        size mismatch for output.weight: copying a param with shape torch.Size([32000, 6656]) from checkpoint, the shape in current model is torch.Size([32000, 5120]).
```

**Comment by randaller** [comment]
@MartinKlefas make sure you have only merged.pth and params.json (and pyarrow folder) in the model folder.
This error indicates torch was unable to load weights correctly, probably there's more than one .pth file or bad .pth file in the model folder.

**Comment by MartinKlefas** [comment]
Thanks I think I moved the wrong json file, as it's working now.
5 minutes between prompt and answer apparently, but that's my fault for having "only" 64GB of RAM and a 2 year old GPU.

**Comment by MartinKlefas** [comment]
Scrub that, it's 5 minutes for each of the bottom progress bars to move. 31 hours to an answer!

![image](https://user-images.githubusercontent.com/12558370/224384551-b7584e37-7026-4344-9fd1-1b93a4f98ba0.png)

**Comment by randaller** [comment]
@MartinKlefas I also feel the pain when trying to inference 65B model :)
